# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyDJ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifyDJ
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'   # If you targeting iOS

pod 'Spartan'
end
