# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'finalproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for finalproject
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'   # If you targeting iOS

pod 'Spartan'
  target 'finalprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'finalprojectUITests' do
    # Pods for testing
  end

end
